.github/workflows/elixir-ci.yaml

`working-directory` at the top levle only affects `run` steps, not other
kinds of actions.

fix: use correct paths for deps cache and Dialyzer

---

ex_cubic_ods_ingestion/lib/ex_cubic_ods_ingestion/start_ingestion.ex

This PR allows loads that don't have a table association to remain in the incoming bucket.

[elixir] fix: error on missing table

---

ex_cubic_ods_ingestion/lib/ex_cubic_ods_ingestion/process_incoming.ex
ex_cubic_ods_ingestion/lib/ex_cubic_ods_ingestion/schema/cubic_ods_load.ex
ex_cubic_ods_ingestion/lib/ex_cubic_ods_ingestion/schema/cubic_ods_table.ex
ex_cubic_ods_ingestion/test/ex_cubic_ods_ingestion/schema/cubic_ods_load_test.exs
ex_cubic_ods_ingestion/test/ex_cubic_ods_ingestion/schema/cubic_ods_table_test.exs
ex_cubic_ods_ingestion/test/ex_cubic_ods_ingestion/start_ingestion_test.exs
ex_cubic_ods_ingestion/test/ex_cubic_ods_ingestion/workers/error_test.exs
ex_cubic_ods_ingestion/test/support/ex_aws.ex
ex_cubic_ods_ingestion/test/support/ex_aws_data.ex

This PR addresses an issue in testing with bucket prefix environment variables being set, specifically the `S3_BUCKET_PREFIX_INCOMING`.
An [Asana ticket](https://app.asana.com/0/1201701089427502/1201998951371780/f) has also been created for an ADR to explain bucket prefixes and their purpose.

[code] fix: tests were not working with prefixes env variables set

---

.editorconfig
.github/workflows/ci.yaml
py_cubic_ods_ingestion/.pylintrc
py_cubic_ods_ingestion/lib/py_cubic_ods_ingestion/ingest_incoming.py
py_cubic_ods_ingestion/lib/py_cubic_ods_ingestion/job_helpers.py
py_cubic_ods_ingestion/poetry.lock
py_cubic_ods_ingestion/pyproject.toml
py_cubic_ods_ingestion/tests/test_job_helpers.py

This PR introduces Pylint to CI for linting python files inside of `py_cubic_ods_ingestion/lib/` and `py_cubic_ods_ingestion/tests/`. Pylint configuration is borrowed from the Google's [Python Style Guide](https://google.github.io/styleguide/pyguide.html) with the only modifications being `max-line-length` and `indent-string`.

[code] feat: add linting with pylint

---

ex_cubic_ods_ingestion/lib/ex_cubic_ods_ingestion/workers/archive.ex
ex_cubic_ods_ingestion/lib/ex_cubic_ods_ingestion/workers/error.ex
ex_cubic_ods_ingestion/lib/ex_cubic_ods_ingestion/workers/ingest.ex
ex_cubic_ods_ingestion/test/ex_cubic_ods_ingestion/workers/ingest_test.exs

This PR adjust the format of the snapshot string to be ISO 8601 compatible. It also fixes a test that didn't have the proper data setup.

[code] fix: snapshot now in iso 8601 + fix test

---

py_cubic_ods_ingestion/lib/py_cubic_ods_ingestion/ingest_incoming.py
py_cubic_ods_ingestion/lib/py_cubic_ods_ingestion/job_helpers.py
py_cubic_ods_ingestion/tests/test_job_helpers.py

This PR addresses an issue where the correct glue table was not being referenced for change tracking loads.

[code] fix: wrong table is referenced for change tracking load

---

.gitignore
.tool-versions
terraform/README.md

This PR add a space for terraform files that may be used during local development. The README.md fill will evolve to include more examples as more stability comes to the platform.

feat: add terraform area for local development resources

---

ex_cubic_ods_ingestion/lib/ex_cubic_ods_ingestion/application.ex
ex_cubic_ods_ingestion/lib/ex_cubic_ods_ingestion/oban_ingest_worker_error.ex
ex_cubic_ods_ingestion/lib/ex_cubic_ods_ingestion/schema/cubic_ods_load.ex
ex_cubic_ods_ingestion/lib/ex_cubic_ods_ingestion/workers/ingest.ex
ex_cubic_ods_ingestion/test/ex_cubic_ods_ingestion/oban_ingest_worker_error_test.exs
ex_cubic_ods_ingestion/test/ex_cubic_ods_ingestion/schema/cubic_ods_load_test.exs

This PR addresses an issue where the Oban worker was not treating a Glue job error as an error in the Oban job.

[code] fix: handle retries on ingest worker error

---

ex_cubic_ingestion/lib/ex_cubic_ingestion/workers/ingest.ex
ex_cubic_ingestion/test/ex_cubic_ingestion/workers/ingest_test.exs
ex_cubic_ingestion/test/support/ex_aws.ex
ex_cubic_ingestion/test/support/test_fixtures.ex

After doing a load test on the ingestion process, I ran into an issue with throttling because of Glue's job concurrency limits. This throttling and Oban's speed created many other errors in the process as Oban moved to execute on other jobs in its pipeline.
Initially, I was hoping to be make a determination on when exactly Glue was actually done with a job, so I can start the next one, but upon further investigation Glue does not actually report this in its `Glue.get_job_run()` which contains the latest status of the job. So ultimately, I resulted in using a "low-tech" approach of just giving AWS time to sync its status across systems.

[elixir] fix: glue throttling because of aggressiveness on oban's part.

---

ex_cubic_ingestion/Dockerfile

This PR updates the checksum for AWS RDS cert as it seems to have been updated. Not sure if there is a way to get notified that this has happened, but don't see any reason to not update it here.

[elixir] fix: checksum for aws rds cert

---

ex_cubic_ingestion/lib/ex_cubic_ingestion/process_ingestion.ex
ex_cubic_ingestion/lib/ex_cubic_ingestion/schema/cubic_load.ex
ex_cubic_ingestion/lib/release_tasks/retry_archive_error.ex
ex_cubic_ingestion/test/ex_cubic_ingestion/schema/cubic_load_test.exs
ex_cubic_ingestion/test/release_tasks/retry_archive_error_test.exs

This PR enables retries of Archive and Error jobs for loads that are stuck in 'archiving' and 'erroring' due to errors from last time the job ran.
There are 2 options for testing this locally:
Note: If you need to setup your local environment, refer to [README.md](https://github.com/mbta/data_platform/blob/main/README.md).
1. Through tests:
```sh
cd ex_cubic_ingestion
mix test
```
2. Through application:
```sh
cd ex_cubic_ingestion
mix release
_build/dev/rel/ex_cubic_ingestion/bin/ex_cubic_ingestion start
_build/dev/rel/ex_cubic_ingestion/bin/ex_cubic_ingestion eval "ReleaseTasks.RetryArchiveError.run()"
```

[elixir] feat: release tasks to retry archive/error jobs that have failed

---

ex_cubic_ingestion/lib/ex_cubic_ingestion/schema/cubic_dmap_dataset.ex
ex_cubic_ingestion/lib/ex_cubic_ingestion/workers/fetch_dmap.ex
ex_cubic_ingestion/lib/release_tasks/application.ex
ex_cubic_ingestion/lib/release_tasks/fetch_dmap.ex
ex_cubic_ingestion/lib/release_tasks/retry_archive_error.ex
ex_cubic_ingestion/lib/release_tasks/schedule_dmap.ex
ex_cubic_ingestion/lib/release_tasks/utilities.ex
ex_cubic_ingestion/test/ex_cubic_ingestion/process_incoming_test.exs
ex_cubic_ingestion/test/ex_cubic_ingestion/workers/fetch_dmap_test.exs
ex_cubic_ingestion/test/release_tasks/fetch_dmap_test.exs

This PR will allow us to re-fetch a certain feed even though it might have been fetched in the past. We'll be able to pass a date that will be used to narrow down the datasets to only the ones that have been updated since that date.
Planning on running with something like this:
```sh
_build/dev/rel/ex_cubic_ingestion/bin/ex_cubic_ingestion eval "ReleaseTasks.FetchDmap.run(%{feed_id: 1, last_updated: ~U[2022-06-20 10:49:50.123456Z]})"
```

[elixir] feat: add fetch dmap release task so we can refetch dataset

---

doc/adr/0007-move-to-string-type-for-all-cubic-provided-data.md

This PR adds an ADR to makes the case for standardizing the Incoming bucket schema columns to all be `string` initially. We're hoping to stabilize the ingestion errors, and only start makings adjustment to the Springboard schemas after we understand the data better.

[doc] feat: ADR for standardizing all Cubic data to string type

---

.env.template
ex_cubic_ingestion/config/runtime.exs

In an attempt to narrow down why the ECS service keeps staring new containers, I'd like to make sure the a crash is not happening because of an aggressive number of connections are going over the limit. See for RDS limits: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.MaxConnections

[elixir] feat: set pool size for dev.

---

ex_cubic_ingestion/priv/repo/migrations/20220725185622_add_indexes_for_loads.exs

This PR adds some indexes to address database performance issues and assist in ruling out slow queries as being the cause of ECS container restarts, as indicated here. A quick explanation of each index below:
`create index("cubic_loads", [:status, :deleted_at])`
There are various areas where we query the loads table by status for further pipeline processing.
`create index("cubic_loads", [:s3_key, :s3_modified, :deleted_at])`
We query the loads table by `s3_key` and `s3_modified` to see if we might have already added a record for the S3 object.
`create index("cubic_ods_load_snapshots", [:load_id, :deleted_at])`
Before we archive or error, we query the load snapshots by the load_id to determine how to store the load in the respective buckets.

[db] add indexes for load tables

---

ex_cubic_ingestion/lib/ex_cubic_ingestion/workers/ingest.ex
ex_cubic_ingestion/priv/repo/migrations/20220801144555_add_svn_incident_ods_table.exs
ex_cubic_ingestion/test/ex_cubic_ingestion/schema/cubic_ods_table_snapshot_test.exs
ex_cubic_ingestion/test/ex_cubic_ingestion/schema/cubic_table_test.exs

This PR adds the SVN_INCIDENT ODS table to be ingested. Table has already been added to the Glue Data Catalog with this deployment: https://github.com/mbta/devops/pull/487

[elixir+db] feat: add EDW.SVN_INCIDENT ODS table rec for ingestion.

---

ex_cubic_ingestion/priv/repo/migrations/20220711142139_add_dmap_feeds.exs

This PR adds the currently available DMAP feeds. The Glue Catalog tables are add in this PR, which will need to be deployed first: https://github.com/mbta/devops/pull/500

[db] add all known DMAP feeds

---

ex_cubic_ingestion/lib/ex_aws/helpers.ex
ex_cubic_ingestion/lib/ex_cubic_ingestion/process_incoming.ex
ex_cubic_ingestion/lib/ex_cubic_ingestion/schema/cubic_load.ex
ex_cubic_ingestion/lib/ex_cubic_ingestion/validators.ex
ex_cubic_ingestion/test/ex_cubic_ingestion/schema/cubic_load_test.exs
ex_cubic_ingestion/test/ex_cubic_ingestion/validators_test.exs
ex_cubic_ingestion/test/support/ex_aws_data.ex

This PR address an issues where a list of s3 objects that is checked against the `cubic_loads` table is rather large and therefore the query is very large. With this PR, we shrink the list down to only objects from the last 24 hours. The objects will have 24 hours to make it through the ingestion process. If the object is in the Incoming bucket for longer than 24 hours, then something has gone wrong.
In our case, the cause of this issue was the ECS task shutting down before the job was finished, and hence leaving loads in  the 'ingesting' status. According to [this](https://github.com/sorentwo/oban/issues/430) Oban should update its state and fail the jobs on a KILL command, but I suspect that the ECS task can't communicate with the DB due to overload.
Overall, this is an improvement to …

[elixir] feat: adjust to querying loads with only recent s3 objects

---

ex_cubic_ingestion/priv/repo/migrations/20220831024427_add_agg_daily_fareprod_dmap_table.exs

This PR adds the DMAP's `agg_daily_fareprod` table for consumption. This table was made available by Cubic in the latest revision, linked to in this Asana ticket: https://app.asana.com/0/1201290014466247/1202348192935957

[db] feat: add new dmap agg_daily_fareprod table for consumption

---

ex_cubic_ingestion/lib/ex_cubic_ingestion/schema/cubic_load.ex
ex_cubic_ingestion/priv/repo/migrations/20220831174254_add_index_for_load_table_id.exs
ex_cubic_ingestion/test/ex_cubic_ingestion/schema/cubic_load_test.exs

This PR continues optimization work for creating a stable ECS container (see [Asana task](https://app.asana.com/0/1201701089427502/1202462260207371)). We introduce a new way of figuring out what is new from the list of S3 objects. We query for the last inserted load record for each table, and only insert S3 objects that are new since the last inserted load, using on the `s3_modified`.

[elixir] feat: insert new objects only if new since last inserted load

---

.github/workflows/ci.yaml
py_cubic_ingestion/.pylintrc
py_cubic_ingestion/poetry.lock
py_cubic_ingestion/pyproject.toml

The Ubuntu environment in Github Actions has been updated, and the Python version has changed from 3.7 to 3.8, which caused a break in our CI pipeline. In this PR, we remove the reliance on the environment's Python, and just use Poetry's virtual environment, where a Python version is specifically set 3.7.12.
We also make a couple of updates for our Pylint configuration to remove no-longer supported settings.

[python] fix: pylint warnings and python version set

---

ex_cubic_ingestion/lib/ex_cubic_ingestion/process_ingestion.ex
ex_cubic_ingestion/lib/ex_cubic_ingestion/schema/cubic_load.ex
ex_cubic_ingestion/test/ex_cubic_ingestion/schema/cubic_load_test.exs

This PR continues the optimizations for running a more stable ECS container, see [Asana task](https://app.asana.com/0/1201290014466247/1202462260207371). For this update, we make a small optimization to limit the query so in the case that there are a lot of loads to be archived/errored, the process doesn't take too long to run.

[elixir] limit query for ready_for_archiving/erroring loads

---

ex_cubic_ingestion/lib/ex_cubic_ingestion/process_ingestion.ex
ex_cubic_ingestion/lib/ex_cubic_ingestion/schema/cubic_load.ex
ex_cubic_ingestion/lib/ex_cubic_ingestion/schema/cubic_table.ex
ex_cubic_ingestion/lib/ex_cubic_ingestion/start_ingestion.ex
ex_cubic_ingestion/priv/repo/migrations/20220901184846_add_index_for_load_status_table_id.exs
ex_cubic_ingestion/test/ex_cubic_ingestion/schema/cubic_load_test.exs
ex_cubic_ingestion/test/ex_cubic_ingestion/schema/cubic_table_test.exs
ex_cubic_ingestion/test/ex_cubic_ingestion/start_ingestion_test.exs

This PR continues the work on optimizing the processes and creating a stable ECS container environment from this [Asana task](https://app.asana.com/0/1201701089427502/1202462260207371). We introduce a different way for querying for 'ready' loads by first getting all the active tables and then querying the 'ready' loads for each table (with a limit). For ODS, we also utilize the last snapshot load, so we only get the loads that we know exist and have not been remove by Qlik during a restart.  An [Asana ticket](https://app.asana.com/0/1201701089427502/1202900902122498) has been created to think through what we do with these 'ready' load records that are now pointing to non-existent objects.
Previously, if there were a lot of 'ready' loads, the process might take a really long time to get to …

[elixir] feat: limit how many ready loads to start ingestion for

---

ex_cubic_ingestion/priv/repo/migrations/20220919141025_add_agg_daily_fareprod_dmap_feed.exs

This PR allows the agg_daily_fareprod to be fetched. It wasn't previously, although it was setup for ingestion with [this PR](https://github.com/mbta/data_platform/pull/76). 
An [Asana task](https://app.asana.com/0/1201701089427502/1203005077372126) has been added to update the docs, so we don't miss this detail in the future.

[db] feat: add agg_daily_fareprod dmap feed

---

ex_cubic_ingestion/priv/repo/migrations/20220921194336_add_more_ods_tables.exs

This PR adds the tables below for ingestion. These tables have already had their schema deployed in the Glue Catalog.
Tables:
EDW.CCH_AFC_TRANSACTION
EDW.SVN_ALM_ASSET
EDW.SVN_ALM_TRANSFER_ORDER
EDW.SVN_ALM_TRANSFER_ORDER_LINE
EDW.SVN_CHANGE_REQUEST
EDW.SVN_CHANGE_TASK
EDW.SVN_CMDB
EDW.SVN_CMDB_REL_CI
EDW.SVN_CMDB_REL_TYPE
EDW.SVN_PROBLEM
EDW.SVN_SC_TASK
EDW.SVN_SM_ORDER
EDW.SVN_SM_TASK
EDW.SVN_SN_STATE
EDW.SVN_SYS_CHOICE
EDW.SVN_TASK
EDW.SVN_TASK_CI
EDW.SVN_U_RMA
EDW.SVN_U_RMA_ACTUAL_FAULT
EDW.SVN_U_RMA_MAIN_WORK
EDW.SVN_U_RMA_REPORTED_FAULT
EDW.SVN_U_SOFTWARE_VERSIONS
EDW.SVN_UFS_REPAIR_CODE_CATEGORIES
EDW.SVN_X_CUTRS_CUST_E_BUS_RTE
EDW.SVN_X_CUTRS_CUST_E_VENUE
EDW.SVN_X_CUTRS_E_CUST_EVENT
EDW.SVN_X_CUTRS_E_M2M_LOC_VEN
EDW.SVN_X_CUTRS_PTT_KPI_DATA

[db] feat: more ODS tables for ingestion

---

ex_cubic_ingestion/config/test.exs
ex_cubic_ingestion/lib/ex_cubic_ingestion/oban_logger.ex
ex_cubic_ingestion/test/ex_cubic_ingestion/oban_logger_test.exs
ex_cubic_ingestion/test/ex_cubic_ingestion/oban_worker_error_test.exs

This PR adds more logging to help in narrowing down exceptions. We usually get this information when a Glue job starts and is running, but if the exception occurs before, we wouldn't have the information. We also add testing for the logs.

[elixir] feat: add info for args when worker has exception

---

ex_cubic_ingestion/config/config.exs
ex_cubic_ingestion/config/prod.exs

This PR addresses a warning on local for not having 'ehmon' as a dependency when running the application. Moving it to the prod configuration avoids this warning and is the correct place to put this.

[elixir] fix: ehmon config in the correct place

---

ex_cubic_ingestion/lib/ex_cubic_ingestion/schema/cubic_ods_load_snapshot.ex
ex_cubic_ingestion/lib/ex_cubic_ingestion/workers/archive.ex
ex_cubic_ingestion/lib/ex_cubic_ingestion/workers/ingest.ex

This PR addresses an issue where while running an 'ingest' job, the app is pulling the snapshot record for the load, and it is receiving back thousands of records. It should really just receive one record back, but due to an issue in the start_ingestion process, these records kept inserting since the load was not being moved out of the 'ready' status.
There is some additional work to make sure this works correctly. They will be addressed as part of [this bug](https://app.asana.com/0/1201701089427502/1202701470464832). More specifically:
1. Need to change 'start_ingestion' to just run through and update ODS table snapshot, insert load snapshot, check schema, and update status of load to 'ready_for_ingesting', all within a transaction.
2. Update 'process_ingestion' to also start 'ingest' …

[elixir] hotfix: get only one record for the ods load snapshot

---

sample_data/cubic/ods_qlik/EDW.SAMPLE/LOAD1.dfm
sample_data/cubic/ods_qlik/EDW.SAMPLE/LOAD2.dfm
sample_data/cubic/ods_qlik/EDW.SAMPLE__ct/20211201-112233444.dfm
sample_data/cubic/ods_qlik/EDW.SAMPLE__ct/20211201-122433444.dfm

Solved the mystery for how we can update rows. Qlik sends over a primary key designation for tables through their `.dfm` files. We will eventually use this to make targeted updates to rows at a final destination beyond the data lake. In this PR, we wanted to update the sample data to show this designation.

[data] fix: add PK info for dfm sample data

---

ex_cubic_ingestion/lib/ex_cubic_ingestion/schema_fetch.ex
ex_cubic_ingestion/lib/ex_cubic_ingestion/validate_incoming.ex
ex_cubic_ingestion/test/ex_cubic_ingestion/schema_fetch_test.exs
ex_cubic_ingestion/test/ex_cubic_ingestion/validate_incoming_test.exs
ex_cubic_ingestion/test/support/ex_aws.ex

This PR addresses an issue where a missing schema file for a data file was causing the validate_incoming process to crash. We now log this issue and allow the process to move to the load to a 'ready_for_erroring' status.

[elixir] fix: ingestion process crashes when missing schema file

---

.tool-versions
ex_cubic_ingestion/priv/repo/migrations/20230508154111_add_language_table.exs

Asana ticket: [[Action Item] Add EDW.LANGUAGE to be ingested](https://app.asana.com/0/1203891745642455/1204461710399181/f)
associated Devops PR: https://github.com/mbta/devops/pull/930
This adds in the ecto migration for ingesting the new language table. The migration appears successful on my testing:
```
11:49:37.071 [info] == Running 20230508154111 ExCubicIngestion.Repo.Migrations.AddLanguageTable.up/0 forward
11:49:37.096 [debug] QUERY OK db=4.8ms
INSERT INTO "cubic_tables" ("is_raw","name","s3_prefix","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5) RETURNING "id" [true, "cubic_ods_qlik__edw_language", "cubic/ods_qlik/EDW.LANGUAGE/", ~U[2023-05-08 15:49:37Z], ~U[2023-05-08 15:49:37Z]]
11:49:37.099 [debug] QUERY OK db=1.4ms
INSERT INTO "cubic_ods_table_snapshots" …
```

[elixir] feat: add language table for ingestion

---

ex_cubic_ingestion/Dockerfile

AWS cert was updated, so this hash needs to be updated to pass this check during deploy

chore: update AWS cert check

---

.github/workflows/elixir-deploy.yaml
.github/workflows/glue-python-deploy.yaml

We are taking the Cubic Data Lake and pipeline live. This change enables us to do production deployments.

[gh] fix: enable deploy actions for live rollout

---

.github/workflows/glue-python-deploy.yaml
.tool-versions
docker/Dockerfile.glue_2_0__local
docker/Dockerfile.glue_3_0__local
py_cubic_ingestion/pyproject.toml

Address two issues:
* Glue build was not working, hence we couldn't deploy.
* Local build was failing due to python3.7 version update and a poetry issue with the latest version.

[env+ga] fix: fix versions for building local and on github

---

ex_cubic_ingestion/config/config.exs
ex_cubic_ingestion/lib/ex_aws/ex_aws_athena.ex
ex_cubic_ingestion/lib/ex_aws/ex_aws_glue.ex
ex_cubic_ingestion/lib/ex_aws/helpers.ex
ex_cubic_ingestion/lib/ex_cubic_ingestion/workers/load_partitions.ex
ex_cubic_ingestion/test/ex_aws/helpers_test.exs
ex_cubic_ingestion/test/ex_cubic_ingestion/workers/load_partitions_test.exs
ex_cubic_ingestion/test/support/ex_aws.ex

Note: This work is related to the deployment of the data pipeline to Production.
The system will need to refresh partitions for some tables in Athena, so we are scheduling a job to run every hour to do so. The reason for the refresh is so our queries will return data under those partitions.
Without this job, we'd have to do something more manual. Not to mention that we'd need permissions to do it against live data.
**This work is dependent on a DevOps PR (forthcoming) to allow permissions for ECS to access Athena.**

[elixir] feat: scheduled loading of partitions in athena

---

ex_cubic_ingestion/config/runtime.exs
ex_cubic_ingestion/lib/ex_aws/ex_aws_athena.ex

By using workgroups, we constrain Athena's access to only Cubic data.
Corresponding DevOps PR: https://github.com/mbta/devops/pull/1254

[elixir] feat: only run athena queries within a workgroup

---

ex_cubic_ingestion/config/config.exs

With the recent changes to permissions, we are able to run these queries manually for production. With this PR, we'll disable them to allow for a better solution through #92

[elixir] fix: disable load partitions for now

---

ex_cubic_ingestion/lib/ex_cubic_ingestion/workers/fetch_dmap.ex
ex_cubic_ingestion/test/ex_cubic_ingestion/workers/fetch_dmap_test.exs
ex_cubic_ingestion/test/support/httpoison.ex

Prevent the logging of any URL information on an error or exception when calling the DMAP feeds, especially API keys being used.

[elixir] feat: hide any url details if dmap errors on fetch

---

ex_cubic_ingestion/lib/ex_cubic_ingestion/workers/fetch_dmap.ex
ex_cubic_ingestion/test/ex_cubic_ingestion/workers/fetch_dmap_test.exs

DMAP feed fetch is failing on production, and I'm not sure why. This PR exposes the response body to see if Cubic is returning an error.

[elixir] feat: get response body on dmap fetch error

---

ex_cubic_ingestion/lib/ex_cubic_ingestion/schema/cubic_table.ex
ex_cubic_ingestion/priv/repo/migrations/20220825021933_update_snapshot_key_for_sample.exs
ex_cubic_ingestion/priv/repo/migrations/20231229210357_add_is_active_for_cubic_tables.exs
ex_cubic_ingestion/test/ex_cubic_ingestion/process_incoming_test.exs
ex_cubic_ingestion/test/ex_cubic_ingestion/schema/cubic_table_test.exs

I'm planning on adding an "Admin" area to manage the "active" status of tables. I will continue to manage migrations in `ex_cubic_ingestion`, so hence this change.
This PR also introduced the filtering by active on incoming loads.

[elixir] feat: add is_active to cubic tables and filter not active from ingestion

---

ex_cubic_ingestion/config/config.exs

DMAP is being ingested but currently the implementation does not have a lot of cases covered that can cause issues for other data being ingested.
The two things currently identified are:
1. There is no schema validation. If the DMAP schema changes the ingestion process is not checking and will fail the glue job.
2. No support for "empty" data in the DMAP feeds. A recent change to the implementation of DMAP allows for empty datasets to show up. I am not currently sure that the ingestion done here accounts for that and/or that Glue is able to ignore it.
For these reasons, and the fact that we have an alternative way to get at DMAP data, I'm opting to turn this off for now.

[elixir] fix: dmap ingestion implementation is not complete, so turn off

---

ex_cubic_ingestion/lib/ex_cubic_ingestion/validate_incoming.ex
ex_cubic_ingestion/lib/ex_cubic_ingestion/workers/ingest.ex
ex_cubic_ingestion/test/ex_cubic_ingestion/validate_incoming_test.exs
ex_cubic_ingestion/test/ex_cubic_ingestion/workers/ingest_test.exs
ex_cubic_ingestion/test/support/ex_aws.ex

* We are turning off glue jobs at this time, as the output it generates are not in use. Most users of the data are looking in the DMAP Import database.
* We also turn off schema validation, as it is done in other pipelines prior to ingestion into the DMAP Import database, and soon ODIN.

[elixir] feat: remove invalid schema check and glue job

---

ex_cubic_ingestion/priv/repo/migrations/20250930200041_add_more_tables_for_ingestion.exs

Checked locally, migration successfully added the following tables:
```
'cubic/ods_qlik/EDW.FRM_CRDB_RECON_SYSCONF_ACQCONF/'
'cubic/ods_qlik/EDW.USE_TRANSACTION/'
```

Adding multiple tables
