mbta/data_platform

- ex_cubic_ods_ingestion/.credo.exs
- ex_cubic_ods_ingestion/config/test.exs
- ex_cubic_ods_ingestion/lib/ex_cubic_ods_ingestion/application.ex
- ex_cubic_ods_ingestion/lib/ex_cubic_ods_ingestion/process_incoming.ex
- ex_cubic_ods_ingestion/lib/ex_cubic_ods_ingestion/repo/migrator.ex
- ex_cubic_ods_ingestion/lib/ex_cubic_ods_ingestion/schema/cubic_ods_load.ex
- ex_cubic_ods_ingestion/test/ex_cubic_ods_ingestion/repo_test.exs
- ex_cubic_ods_ingestion/test/support/ex_aws_data.ex
This should help the code be more Elixir-y overall, rather than needing
to rely on review comments.
> fix: make Credo stricter

- .github/workflows/elixir-deploy.yaml
- .github/workflows/glue-python-deploy.yaml
Adding these 'empty' workflows, so we can merge them in the main branch, allowing us to iterate on them in other PRs.
> [infra] feat: add workflows for elixir/glue deploys

- ex_cubic_ods_ingestion/priv/repo/migrations/20220331155057_add_edw_sample_table_record.exs
[Asana](https://app.asana.com/0/1201701089427502/1202057214831463)
This PR adds the EDW.SAMPLE table record to the CubicOdsTable database table.
> migration: add sample table as record in cubic_ods_tables

- ex_cubic_ods_ingestion/config/runtime.exs
- ex_cubic_ods_ingestion/config/test.exs
- ex_cubic_ods_ingestion/test/ex_cubic_ods_ingestion/process_ingestion_test.exs
- ex_cubic_ods_ingestion/test/ex_cubic_ods_ingestion/workers/ingest_test.exs
This PR fixes config issues with dev/test database configurations and prod. It also refactors some tests to conform with how tests are setup in general.
> [code] fix: broken testing due to wrong config setup

- ex_cubic_ods_ingestion/Dockerfile
- ex_cubic_ods_ingestion/lib/ex_cubic_ods_ingestion/repo.ex
- ex_cubic_ods_ingestion/mix.exs
- ex_cubic_ods_ingestion/test/ex_cubic_ods_ingestion/repo_test.exs
For reference: [Asana](https://app.asana.com/0/1201701089427502/1202057217031146)
This PR fixes warnings when Elixir app connects to RDS through SSL.
> [code] fix: rds has ssl warning upon connection

- ex_cubic_ods_ingestion/Dockerfile
This PR fixes the path where the cert is placed, so it can be referenced correctly on release.
> [code] fix: adjust where the cert is placed before release

- .tool-versions
- README.md
- docker-compose.yml
- docker/Dockerfile.glue_2_0__local
- docker/Dockerfile.glue_3_0__local
- py_cubic_ods_ingestion/lib/py_cubic_ods_ingestion/ingest_incoming.py
- py_cubic_ods_ingestion/lib/py_cubic_ods_ingestion/job_helpers.py
- py_cubic_ods_ingestion/poetry.lock
- py_cubic_ods_ingestion/pyproject.toml
- py_cubic_ods_ingestion/tests/test_job_helpers.py
For reference: [Asana](https://app.asana.com/0/1201701089427502/1202035441548840)
This PR adds PySpark testing to the Glue job code. It also adds a container for Glue 3.0 [WIP].
> [py_cubic_ods_ingestion] feat: add pyspark testing + glue containers

- .editorconfig
- doc/adr/0005-refactoring-ingestion-for-all-data.md
This PR introduces an ADR for the refactoring effort for allowing the ingestion process to account for DMAP/Kafka data.
> [doc] feat: ADR for refactoring ingestion to account for DMAP/Kafka data

- doc/adr/0006-fetching-cubic-dmap-records.md
For reference: [Asana](https://app.asana.com/0/1201701089427502/1202207406750018)
This PR introduce an ADR document for how to implement the fetching of DMAP data.
> [doc] feat: ADR for implementation of fetching DMAP data

- ex_cubic_ingestion/priv/repo/migrations/20220518173552_add_rest_ods_table_records.exs
This PR adds a migration for adding the rest of the ODS tables to the ingestion process.
> [db] feat: add more ODS table records

- ex_cubic_ingestion/config/config.exs
- ex_cubic_ingestion/config/test.exs
- ex_cubic_ingestion/lib/ex_cubic_ingestion/application.ex
- ex_cubic_ingestion/lib/mix/tasks/schedule_dmap.ex
- ex_cubic_ingestion/mix.exs
This PR serves as a proof of concept for running Cubic Ingestion tasks. I'm hoping to use what I learn here for attempting retries of glue jobs that have failed.
> [elixir] feat: ability to execute a schedule DMAP fetching upon running the task.

- .env.template
- README.md
- terraform/README.md
This PR adds more documentation for setting up a local environment.
> [doc] feat: update local setup READMEs

- ex_cubic_ingestion/lib/ex_cubic_ingestion/schema/cubic_load.ex
- ex_cubic_ingestion/lib/ex_cubic_ingestion/schema/cubic_table.ex
- ex_cubic_ingestion/lib/ex_cubic_ingestion/workers/ingest.ex
- ex_cubic_ingestion/priv/repo/migrations/20220629190702_add_is_raw_for_tables_loads.exs
- ex_cubic_ingestion/test/ex_cubic_ingestion/schema/cubic_load_test.exs
- ex_cubic_ingestion/test/ex_cubic_ingestion/workers/ingest_test.exs
- ex_cubic_ingestion/test/support/test_fixtures.ex
- py_cubic_ingestion/lib/py_cubic_ingestion/ingest_incoming.py
- py_cubic_ingestion/lib/py_cubic_ingestion/job_helpers.py
- py_cubic_ingestion/tests/test_job_helpers.py
This PR has code to support the implementation of this [ADR](https://github.com/mbta/data_platform/blob/main/doc/adr/0007-move-to-string-type-for-all-cubic-provided-data.md). Please take a look, before reviewing.
> [elixir+python] add raw for unprocessed springboard loads

- ex_cubic_ingestion/lib/ex_cubic_ingestion/start_ingestion.ex
- ex_cubic_ingestion/test/ex_cubic_ingestion/start_ingestion_test.exs
This PR is updated from this [already approved PR](https://github.com/mbta/data_platform/pull/42).
> [elixir] re-add chunking by size and number

- ex_cubic_ingestion/config/config.exs
- ex_cubic_ingestion/config/test.exs
- ex_cubic_ingestion/lib/ex_cubic_ingestion/process_ingestion.ex
- ex_cubic_ingestion/lib/ex_cubic_ingestion/start_ingestion.ex
- ex_cubic_ingestion/lib/ex_cubic_ingestion/workers/ingest.ex
This PR makes some adjustments to timers and Oban queues, in order to ease the load on the container.
> [elixir] feat: adjust timers and oban async queue

- ex_cubic_ingestion/Dockerfile
- ex_cubic_ingestion/priv/repo/migrations/20230202193320_add_journal_entry_table_for_ingestion.exs
Cubic is sending a table containing journal entry information. We'd like to ingest it, so adding the db record to allow for fetching it from S3.
> [elixir] feat: add journal entry table for ingestion

- ex_cubic_ingestion/priv/repo/migrations/20240503150554_add_kpi_monthly_sldc_table.exs
New table added for ingestion.
This follows the process in this document: https://www.notion.so/mbta-downtown-crossing/Adding-a-New-Table-for-Ingestion-ec2f44a98f864a18929e4db4b48c931a
> [elixir] feat: add kpi monthly sldc table to be ingested

- ex_cubic_ingestion/priv/repo/migrations/20240805153811_add_member_dimension_row.exs
New table to ingest: EDW.MEMBER_DIMENSION
Follows the process here: https://www.notion.so/mbta-downtown-crossing/Adding-a-New-Table-for-Ingestion-ec2f44a98f864a18929e4db4b48c931a
> [elixir] feat: add member dimension table for processing

- .github/workflows/ci.yaml
- ex_cubic_ingestion/Dockerfile
- ex_cubic_ingestion/priv/repo/migrations/20240930181923_add_device_last_state_table.exs
New table to ingest.
Following guide here: https://www.notion.so/mbta-downtown-crossing/Adding-a-New-Table-for-Ingestion-ec2f44a98f864a18929e4db4b48c931a
> [elixir] chore: new EDW.DEVICE_LAST_STATE table to ingest

- ex_cubic_ingestion/Dockerfile
> chore: update rds checksum
